### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [lambdalisue/collon.zsh#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by lambdalisue** [comment]
I'll add a MIT license 👍

**Comment by lambdalisue** [comment]
Done. https://github.com/lambdalisue/collon.zsh/blob/master/LICENSE

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/827

**Comment by unixorn** [comment]
Thanks
